### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by s-cork** [dimfeld/codemirror-json5#3]
It seems off by a line to me
If I switch in @codemirror/lang-json the folding works as expected

![c3ddff403b97615d3b739e8ee7624b64fb11449f](https://github.com/dimfeld/codemirror-json5/assets/36813890/b5495c9d-71ae-436a-87dd-fab83180739c)

**Comment by dimfeld** [comment]
Published 1.0.3 which requires the new version of lezer-json5. Thanks for the fix!
